version: '3.9'

services:

  db:
    image: postgres:16
    container_name: cryptocop_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cryptocop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - cryptocop-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: ./Cryptocop.Software.API
    container_name: api
    depends_on:
      db:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=cryptocop_db;Username=postgres;Password=postgres
      - ASPNETCORE_URLS=http://+:5001
    ports:
      - "5001:5001"
    networks:
      - cryptocop-network

volumes:
  postgres_data:

networks:
  cryptocop-network:
    driver: bridge